In [1]:
 !pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\chint\ml_workshop_env\lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\chint\ml_workshop_env\lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in c:\users\chint\ml_workshop_env\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in c:\users\chint\ml_workshop_env\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\chint\ml_workshop_env\lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\chint\ml_workshop_env\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip available: 22.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd
import sklearn

In [3]:
data=pd.DataFrame({'Price_USA':[80,50,140,25],
                   'Price_INR':[5000,7000,12000,3000]})
data

   Price_USA  Price_INR
0         80       5000
1         50       7000
2        140      12000
3         25       3000

In [4]:
data['Price_USA_minmax'] = (data['Price_USA'] - data['Price_USA'].min())/(data['Price_USA'].max() - data['Price_USA'].min())
data

   Price_USA  Price_INR  Price_USA_minmax
0         80       5000          0.478261
1         50       7000          0.217391
2        140      12000          1.000000
3         25       3000          0.000000

In [5]:
data['Price_INR_minmax'] = (data['Price_INR'] - data['Price_INR'].min())/(data['Price_INR'].max() - data['Price_INR'].min())
data

   Price_USA  Price_INR  Price_USA_minmax  Price_INR_minmax
0         80       5000          0.478261          0.222222
1         50       7000          0.217391          0.444444
2        140      12000          1.000000          1.000000
3         25       3000          0.000000          0.000000

In [6]:
import sklearn

In [7]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [8]:
min_max=MinMaxScaler()

In [9]:
data['Price_USA_minsk'] = min_max.fit_transform(data[['Price_USA']])
data

   Price_USA  Price_INR  Price_USA_minmax  Price_INR_minmax  Price_USA_minsk
0         80       5000          0.478261          0.222222         0.478261
1         50       7000          0.217391          0.444444         0.217391
2        140      12000          1.000000          1.000000         1.000000
3         25       3000          0.000000          0.000000         0.000000

In [10]:
data['Price_INR_minsk'] = min_max.fit_transform(data[['Price_INR']])
data

,Price_USA,Price_INR,Price_USA_minmax,Price_INR_minmax,Price_USA_minsk,Price_INR_minsk
0,80,5000,0.478261,0.222222,0.478261,0.222222
1,50,7000,0.217391,0.444444,0.217391,0.444444
2,140,12000,1.000000,1.000000,1.000000,1.000000
3,25,3000,0.000000,0.000000,0.000000,0.000000

In [11]:
data['Price_USA_std'] = (data['Price_USA']-data['Price_USA'].mean())/(data['Price_USA'].std())
data

,Price_USA,Price_INR,Price_USA_minmax,Price_INR_minmax,Price_USA_minsk,Price_INR_minsk,Price_USA_std
0,80,5000,0.478261,0.222222,0.478261,0.222222,0.126108
1,50,7000,0.217391,0.444444,0.217391,0.444444,-0.479212
2,140,12000,1.000000,1.000000,1.000000,1.000000,1.336748
3,25,3000,0.000000,0.000000,0.000000,0.000000,-0.983645

In [12]:
data['Price_INR_std'] = (data['Price_INR']-data['Price_INR'].mean())/(data['Price_INR'].std())
data

,Price_USA,Price_INR,Price_USA_minmax,Price_INR_minmax,Price_USA_minsk,Price_INR_minsk,Price_USA_std,Price_INR_std
0,80,5000,0.478261,0.222222,0.478261,0.222222,0.126108,-0.453108
1,50,7000,0.217391,0.444444,0.217391,0.444444,-0.479212,0.064730
2,140,12000,1.000000,1.000000,1.000000,1.000000,1.336748,1.359325
3,25,3000,0.000000,0.000000,0.000000,0.000000,-0.983645,-0.970947

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
Scaler=StandardScaler()

In [15]:
data['Price_USA_Scaler']=Scaler.fit_transform(data[['Price_USA']])
data

,Price_USA,Price_INR,Price_USA_minmax,Price_INR_minmax,Price_USA_minsk,Price_INR_minsk,Price_USA_std,Price_INR_std,Price_USA_Scaler
0,80,5000,0.478261,0.222222,0.478261,0.222222,0.126108,-0.453108,0.145617
1,50,7000,0.217391,0.444444,0.217391,0.444444,-0.479212,0.064730,-0.553346
2,140,12000,1.000000,1.000000,1.000000,1.000000,1.336748,1.359325,1.543544
3,25,3000,0.000000,0.000000,0.000000,0.000000,-0.983645,-0.970947,-1.135815

In [16]:
data['Price_INR_Scaler']=Scaler.fit_transform(data[['Price_INR']])
data

,Price_USA,Price_INR,Price_USA_minmax,Price_INR_minmax,Price_USA_minsk,Price_INR_minsk,Price_USA_std,Price_INR_std,Price_USA_Scaler,Price_INR_Scaler
0,80,5000,0.478261,0.222222,0.478261,0.222222,0.126108,-0.453108,0.145617,-0.523205
1,50,7000,0.217391,0.444444,0.217391,0.444444,-0.479212,0.064730,-0.553346,0.074744
2,140,12000,1.000000,1.000000,1.000000,1.000000,1.336748,1.359325,1.543544,1.569614
3,25,3000,0.000000,0.000000,0.000000,0.000000,-0.983645,-0.970947,-1.135815,-1.121153

In [17]:
from sklearn.preprocessing import RobustScaler

In [18]:
robust=RobustScaler()

In [19]:
data['Price_USA_robust']=robust.fit_transform(data[['Price_USA']])
data['Price_USA_robust']
data['Price_INR_robust']=robust.fit_transform(data[['Price_INR']])
data['Price_INR_robust']

0   -0.266667
1    0.266667
2    1.600000
3   -0.800000
Name: Price_INR_robust, dtype: float64

In [20]:
!pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Requirement already satisfied: pandas>=1.0.0 in c:\users\chint\ml_workshop_env\lib\site-packages (from ucimlrepo) (3.0.5)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\chint\ml_workshop_env\lib\site-packages (from ucimlrepo) (2026.7.22)
Requirement already satisfied: numpy>=1.26.0 in c:\users\chint\ml_workshop_env\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\chint\ml_workshop_env\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\chint\ml_workshop_env\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\chint\ml_workshop_env\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

[notice] A new release of pip available: 22.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [24]:
!pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
     ------------------------------------ 294.9/294.9 kB 958.5 kB/s eta 0:00:00
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\chint\ml_workshop_env\lib\site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in c:\users\chint\ml_workshop_env\lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\chint\ml_workshop_env\lib\site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\chint\ml_workshop_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\chint\ml_workshop_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\chint\ml_workshop_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\chint\ml_workshop_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\chint\ml_workshop_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in c:\users\chint\ml_workshop_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\chint\ml_workshop_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\chint\ml_workshop_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\chint\ml_workshop_env\lib\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\chint\ml_workshop_env\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

[notice] A new release of pip available: 22.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
from ucimlrepo import fetch_ucirepo
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import OneHotEncoder,PolynomialFeatures
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
sns.set_style(style='whitegrid')

NameError: name 'sns' is not defined

In [ ]:
data = fetch_ucirepo(id=9)
data
X= data.data.features.copy()
X
y=data.data.targets['mpg']
y

In [ ]:
X['origin'].unique();
X['horsepower'].unique()

In [ ]:
X.info()

In [ ]:
X['horsepower']=pd.to_numeric(X['horsepower'],errors='coerce')
X['origin']=X['origin'].astype(str)

In [ ]:
X.info()

In [ ]:

numerical_features=['cylinders','displacement','horsepower','weight','acceleration','model_year']
categorical_features=['origin']
X=X[numerical_features+categorical_features]
X.info()
X.shape

In [ ]:
df=X.copy()
df['mpg']= y

In [ ]:
df

In [ ]:
fig, axes = plt.subplots(1, 3, figsize=(10, 3))
sns.histplot(df['mpg'],kde=True,ax=axes[0],color='lightblue')
sns.histplot(df['mpg'],kde=True,ax=axes[1],color='blue')
sns.histplot(df['mpg'],kde=True,ax=axes[2],color='navy')

In [ ]:
fig, axes = plt.subplots(1, 3, figsize=(10, 3))
sns.histplot(df['mpg'],kde=True,ax=axes[0],color='coral')
axes[0].set_title("MPG DISTRIBUTION")
sns.scatterplot(x=df['weight'],y=df['mpg'],ax=axes[1],color='gold')
axes[1].set_title("Weight VS MPG Distribution")
sns.scatterplot(x=df['horsepower'],y=df['mpg'],ax=axes[2],color='silver')
axes[2].set_title("Horsepower VS MPG Distribution")

In [ ]:
plt.figure(figsize=(10,3))
sns.heatmap(df.select_dtypes(include=np.number).corr(),annot=True)

In [ ]:
plt.figure(figsize=(10, 3))
sns.heatmap(df.select_dtypes(include=np.number).corr(),annot=True,cmap='coolwarm',center=0)
plt.title("Correlation Matrix")
plt.tight_layout()
plt.show()

In [ ]:
#print(X)
#print(y)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
print('\n Train Test Split')
print("Training Data",len(X_train))
print("Training Data",len(X_test))
#print(X_train)

In [ ]:
def evaluate(model_name,actual,predicted):
    mse=mean_squared_error(actual,predicted)
    mae=mean_absolute_error(actual,predicted)

    return {'Model_Name':model_name,
            'MAE':mae,
            'MSE':mse,
            'RMSE':np.sqrt(mse),
            'R2-score':r2_score(actual,predicted)}
results=[]

In [ ]:
baseline_predictions=np.full(len(y_test),y_train.mean())
results.append(evaluate("Mean baseline",y_test,baseline_predictions))

In [ ]:
simple_model=LinearRegression()
simple_model.fit(X_train[['acceleration']],y_train)
simple_model_predictions=simple_model.predict(X_test[['acceleration']])
results.append(evaluate("simple Linear Regression:Acceleration",y_test,simple_model_predictions))
print(len(results))

In [ ]:
print(f'Simple Linear Regression Equation')
print(f"Predicted MPG = {simple_model.intercept_}=({simple_model.coef_[0]})*acceleration")

In [ ]:
simple_model=LinearRegression()
simple_model.fit(X_train[['weight']],y_train)
simple_model_predictions=simple_model.predict(X_test[['weight']])
results.append(evaluate("simple Linear Regression:weight",y_test,simple_model_predictions))
print(len(results))

In [ ]:
print(f'simple Linear Regression Equation')
print(f"predicted MPG ={simple_model.intercept_}+({simple_model.coef_[0]}*weight")

In [ ]:
simple_model=LinearRegression()
simple_model.fit(X_train[['cylinders']],y_train)
simple_model_predictions=simple_model.predict(X_test[['cylinders']])
results.append(evaluate("simple Linear Regression:cylinders",y_test,simple_model_predictions))
print(len(results))

In [ ]:
print(f'Simple Linear Regression Equation')
print(f"Predicted MPG = {simple_model.intercept_}=({simple_model.coef_[0]})*cylinders")

In [ ]:
simple_model=LinearRegression()
simple_model.fit(X_train[['displacement']],y_train)
simple_model_predictions=simple_model.predict(X_test[['displacement']])
results.append(evaluate("simple Linear Regression:displacement",y_test,simple_model_predictions))
print(len(results))

In [ ]:
print(f'Simple Linear Regression Equation')
print(f"Predicted MPG = {simple_model.intercept_}=({simple_model.coef_[0]})*displacement")

In [ ]:
X_train['horsepower'] = X_train['horsepower'].fillna(X_train['horsepower'].median())
X_test['horsepower'] = X_test['horsepower'].fillna(X_train['horsepower'].median())

# Simple Linear Regression
simple_model = LinearRegression()

simple_model.fit(X_train[['horsepower']], y_train)

simple_model_predictions = simple_model.predict(X_test[['horsepower']])

results.append(
    evaluate(
        "simple Linear Regression: horsepower",
        y_test,
        simple_model_predictions
    )
)

print(len(results))

In [ ]:
print(f'Simple Linear Regression Equation')
print(f"Predicted MPG = {simple_model.intercept_}=({simple_model.coef_[0]})*horsepower")

In [ ]:
results